name: rinha-backend-2026

services:
  lb:
    image: haproxy:2.9-alpine
    command: ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg", "-db"]
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: 20MB

  api01:
    image: acauhi/rinha-2026-rust@sha256:f486d378c4b444a9f554f69448669ba6bd1391951c45a8823dbc4c1df7abd40a
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: 165MB

  api02:
    image: acauhi/rinha-2026-rust@sha256:f486d378c4b444a9f554f69448669ba6bd1391951c45a8823dbc4c1df7abd40a
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: 165MB
