name: rinha-backend-2026

services:
  lb:
    image: haproxy:2.9-alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: 20MB

  api01:
    image: acauhi/rinha-2026-rust@sha256:5d0ec68f58c5b2fbe9069c57a9f49ea978ba83b45e26055b2bae99b9b7a169e8
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: 165MB

  api02:
    image: acauhi/rinha-2026-rust@sha256:5d0ec68f58c5b2fbe9069c57a9f49ea978ba83b45e26055b2bae99b9b7a169e8
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: 165MB
